service:
  image: 'dockercloud/haproxy:latest'
  container_name: "myservice"
  cpu_shares: 4096
  restart: "on-failure:2"
  ports:
    - '80:80'
  links:
    - "service1:web1"
    - "service2:web2"
    
    
service1:
  image: startx/sxapi:latest
  container_name: "myservice-service1"
  cpu_shares: 4096
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  ports:
    - "80:8080"
  volumes:
    - "~/sxapi-data:/data"
    - "./:/conf"
    
service2:
  image: startx/sxapi:latest
  container_name: "myservice-service2"
  cpu_shares: 4096
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  ports:
    - "80:8080"
  volumes:
    - "~/sxapi-data:/data"
    - "./:/conf"