service:
  image: startx/sxapi:latest
  container_name: "myservice"
  cpu_shares: 4096
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  volumes:
    - "~/sxapi-data:/data"
    - "./:/conf"