simple:
  image: startx/sxapi:latest
  container_name: "sxapi-sample-simple-latest"
  cpu_shares: 4096
  cpuset: "0"
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  ports:
    - "8080:19777"
  volumes:
    - "~/sxapi-data:/data"
    - "./:/conf"