simple-full:
  extends:
    file: full/docker-compose.yml
    service: "full"
  container_name: "sxapi-sample-simple-full"
  ports:
    - "1981:8080"
    
simple-hello:
  extends:
    file: hello/docker-compose.yml
    service: "hello"
  container_name: "sxapi-sample-simple-hello"
  ports:
    - "1982:8080"
      
simple-html:
  extends:
    file: html/docker-compose.yml
    service: "html"
  container_name: "sxapi-sample-simple-html"
  ports:
    - "1983:8080"
      
simple-json:
  extends:
    file: json/docker-compose.yml
    service: "json"
  container_name: "sxapi-sample-simple-json"
  ports:
    - "1984:8080"
      
simple-module:
  extends:
    file: module/docker-compose.yml
    service: "module"
  container_name: "sxapi-sample-simple-module"
  ports:
    - "1985:8080"
      
simple-ping:
  extends:
    file: ping/docker-compose.yml
    service: "ping"
  container_name: "sxapi-sample-simple-ping"
  ports:
    - "1986:8080"
    
simple-txt:
  extends:
    file: txt/docker-compose.yml
    service: "txt"
  container_name: "sxapi-sample-simple-txt"
  ports:
    - "1987:8080"
    
    
