simple-full:
  extends:
    file: simple/docker-compose.yml
    service: "simple-full"
  container_name: "sxapi-sample-simple-full-master"
  ports:
    - "8081:19777"

simple-hello:
  extends:
    file: simple/docker-compose.yml
    service: "simple-hello"
  container_name: "sxapi-sample-simple-hello-master"
  ports:
    - "8082:19777"
  
simple-html:
  extends:
    file: simple/docker-compose.yml
    service: "simple-html"
  container_name: "sxapi-sample-simple-html-master"
  ports:
    - "8083:19777"
  
simple-json:
  extends:
    file: simple/docker-compose.yml
    service: "simple-json"
  container_name: "sxapi-sample-simple-json-master"
  ports:
    - "8084:19777"
  
simple-module:
  extends:
    file: simple/docker-compose.yml
    service: "simple-module"
  container_name: "sxapi-sample-simple-module-master"
  ports:
    - "8085:19777"
  
simple-ping:
  extends:
    file: simple/docker-compose.yml
    service: "simple-ping"
  container_name: "sxapi-sample-simple-ping-master"
  ports:
    - "8086:19777"
  
simple-txt:
  extends:
    file: simple/docker-compose.yml
    service: "simple-txt"
  container_name: "sxapi-sample-simple-txt-master"
  ports:
    - "8087:19777"
  

db-mysql:
  extends:
    file: db/docker-compose.yml
    service: "db-mysql"
  container_name: "sxapi-sample-db-mysql-master"
  ports:
    - "8091:19777"
