service:
  image: startx/sxapi:0.0.8
  container_name: "myservice-service1"
  cpu_shares: 4096
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  ports:
    - "8081:8080"
  volumes:
    - "~/sxapi-data:/data"
    - "./:/conf"