sxapi:
  image: startx/sxapi:0.0.8
  container_name: "sxapi-myapi"
  cpu_shares: 4096
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  privileged: true
  volumes:
    - "~/sxapi-data:/data"
    - "./:/conf"
    
couchbase:
  image: couchbase:latest
  ports:
    - "8091-8094:8091-8094"
    - "11210:11210"

redis:
  image: redis:latest
  ports:
    - "6379:6379"